<a href="https://colab.research.google.com/github/Sara-flores/Sara-flores/blob/main/Eliminaci%C3%B3n_gaussiana_con_pivoteo_parcial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:


# Función para redondear a 4 dígitos significativos
def round_four_digits(value):
    return round(value, 4)

# Función para realizar eliminación gaussiana con pivoteo parcial
def gauss_elimination(A):
    n = len(A)

    # Eliminación hacia adelante con pivoteo parcial
    for i in range(n):
        # Pivoteo parcial: Encontrar el máximo valor absoluto en la columna i
        max_row = i + np.argmax(abs(A[i:n, i]))
        if max_row != i:
            # Intercambiar filas
            A[[i, max_row]] = A[[max_row, i]]

        # Redondear el pivote
        A[i, i] = round_four_digits(A[i, i])

        # Hacer ceros debajo del pivote
        for j in range(i + 1, n):
            if A[j, i] != 0:
                factor = A[j, i] / A[i, i]
                A[j, i:] = A[j, i:] - factor * A[i, i:]
                # Redondear cada elemento de la fila resultante
                A[j] = np.round(A[j], 4)

    return A

# Función para sustitución hacia atrás
def back_substitution(A):
    n = len(A)
    x = np.zeros(n)

    # Sustitución hacia atrás
    for i in range(n-1, -1, -1):
        x[i] = A[i, -1] / A[i, i]
        x[i] = round_four_digits(x[i])  # Redondeo de la solución
        for j in range(i-1, -1, -1):
            A[j, -1] -= A[j, i] * x[i]
            A[j, -1] = round_four_digits(A[j, -1])  # Redondeo de la columna aumentada

    return x

In [3]:
# Definir la matriz aumentada del sistema
A = np.array([
    [0.003000, 59.14, 59.17],
    [5.291, -6.130, 46.78]
], dtype=float)

# Mostrar la matriz antes de la eliminación
print("Matriz aumentada inicial:")
print(A)

# Realizar eliminación gaussiana con pivoteo parcial
A = gauss_elimination(A)

# Mostrar la matriz después de la eliminación gaussiana
print("\nMatriz después de eliminación gaussiana con pivoteo:")
print(A)

# Realizar sustitución hacia atrás para encontrar la solución
solucion = back_substitution(A)

# Mostrar la solución
print("\nLa solución es:")
for i in range(len(solucion)):
    print(f"x{i+1} = {solucion[i]}")

# Comparar con la solución exacta
solucion_exacta = [10.00, 1.000]
print("\nComparación con la solución exacta:")
for i in range(len(solucion)):
    print(f"x{i+1} (calculado) = {solucion[i]}, x{i+1} (exacto) = {solucion_exacta[i]}")

Matriz aumentada inicial:
[[ 3.000e-03  5.914e+01  5.917e+01]
 [ 5.291e+00 -6.130e+00  4.678e+01]]

Matriz después de eliminación gaussiana con pivoteo:
[[ 5.291  -6.13   46.78  ]
 [ 0.     59.1435 59.1435]]

La solución es:
x1 = 10.0
x2 = 1.0

Comparación con la solución exacta:
x1 (calculado) = 10.0, x1 (exacto) = 10.0
x2 (calculado) = 1.0, x2 (exacto) = 1.0
