<a href="https://colab.research.google.com/github/Sara-flores/Sara-flores/blob/main/Eliminaci%C3%B3n_gaussiana_con_sustituci%C3%B3n_hacia_atr%C3%A1s.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
# Definir la matriz aumentada del sistema
A = np.array([
    [1, -1, 2, -1, -8],
    [2, -2, 3, -3, -20],
    [1, 1, 1, 0, -2],
    [1, -1, 4, 3, 4]
], dtype=float)

# Función para realizar eliminación gaussiana
def gauss_elimination(A):
    n = len(A)

    # Realizamos la eliminación hacia adelante
    for i in range(n):
        # Asegurarse de que el pivote A[i][i] no sea cero
        if A[i][i] == 0:
            for j in range(i+1, n):
                if A[j][i] != 0:
                    # Intercambiamos filas
                    A[[i, j]] = A[[j, i]]
                    break

        # Hacer ceros debajo del pivote
        for j in range(i+1, n):
            if A[j][i] != 0:
                factor = A[j][i] / A[i][i]
                A[j, i:] -= factor * A[i, i:]

    return A

# Función para realizar sustitución hacia atrás
def back_substitution(A):
    n = len(A)
    x = np.zeros(n)

    # Comenzamos con la última fila y vamos hacia arriba
    for i in range(n-1, -1, -1):
        x[i] = A[i, -1] / A[i, i]
        for j in range(i-1, -1, -1):
            A[j, -1] -= A[j, i] * x[i]

    return x

In [3]:
# Mostrar la matriz antes de la eliminación
print("Matriz aumentada inicial:")
print(A)

# Realizar eliminación gaussiana
A = gauss_elimination(A)

# Mostrar la matriz después de la eliminación gaussiana
print("\nMatriz después de eliminación gaussiana:")
print(A)

# Realizar sustitución hacia atrás para encontrar la solución
solucion = back_substitution(A)

# Mostrar la solución
print("\nLa solución es:")
for i in range(len(solucion)):
    print(f"x{i+1} = {solucion[i]}")

Matriz aumentada inicial:
[[  1.  -1.   2.  -1.  -8.]
 [  2.  -2.   3.  -3. -20.]
 [  1.   1.   1.   0.  -2.]
 [  1.  -1.   4.   3.   4.]]

Matriz después de eliminación gaussiana:
[[ 1. -1.  2. -1. -8.]
 [ 0.  2. -1.  1.  6.]
 [ 0.  0. -1. -1. -4.]
 [ 0.  0.  0.  2.  4.]]

La solución es:
x1 = -7.0
x2 = 3.0
x3 = 2.0
x4 = 2.0
