<a href="https://colab.research.google.com/github/Sara-flores/Sara-flores/blob/main/Factorizaci%C3%B3n_LU.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [4]:

# Matriz A y vector b
A = np.array([[1, 1, 0, 3],
              [2, 1, -1, 1],
              [3, -1, -1, 2],
              [-1, 2, 3, -1]], dtype=float)

b = np.array([4, 1, -3, 4], dtype=float)

# Función para realizar la factorización LU
def lu_decomposition(A):
    n = A.shape[0]
    L = np.zeros_like(A)
    U = np.zeros_like(A)

    for i in range(n):
        # Componente U
        for j in range(i, n):
            U[i, j] = A[i, j] - np.dot(L[i, :i], U[:i, j])

        # Componente L
        for j in range(i + 1, n):
            L[j, i] = (A[j, i] - np.dot(L[j, :i], U[:i, i])) / U[i, i]

        # Diagonal de L es 1
        L[i, i] = 1

    return L, U

# Factorización LU
L, U = lu_decomposition(A)

# Mostrar L y U
print("Matriz L:")
print(L)
print("\nMatriz U:")
print(U)

# Resolución del sistema Ax = b utilizando la factorización LU
# 1. Resolver Lc = b usando sustitución hacia adelante
def forward_substitution(L, b):
    n = L.shape[0]
    c = np.zeros_like(b)
    for i in range(n):
        c[i] = b[i] - np.dot(L[i, :i], c[:i])
    return c

# 2. Resolver Ux = c usando sustitución hacia atrás
def backward_substitution(U, c):
    n = U.shape[0]
    x = np.zeros_like(c)
    for i in range(n-1, -1, -1):
        x[i] = (c[i] - np.dot(U[i, i+1:], x[i+1:])) / U[i, i]
    return x

Matriz L:
[[ 1.  0.  0.  0.]
 [ 2.  1.  0.  0.]
 [ 3.  4.  1.  0.]
 [-1. -3.  0.  1.]]

Matriz U:
[[  1.   1.   0.   3.]
 [  0.  -1.  -1.  -5.]
 [  0.   0.   3.  13.]
 [  0.   0.   0. -13.]]


In [5]:
# Paso 1: Resolver Lc = b
c = forward_substitution(L, b)

# Paso 2: Resolver Ux = c
x = backward_substitution(U, c)

# Mostrar la solución
print("\nSolución x:")
print(x)


Solución x:
[-1.  2.  0.  1.]
